### ISSUE TITLE
Crashed with nil pointer when putting a key to a cluster of 2 replicas and one replica is down. (not reproducible)

### ISSUE THREAD

**Issue by lming** [chrislusf/vasto#11]
```
I0129 14:47:31.514926   23375 master_event_processor.go:56] [master] + client  from 127.0.0.1:62432 keyspace(clst)
E0129 14:50:26.104690   23375 retry.go:22] shard clst.1.0 normal follow 0.0 failed: pull changes: rpc error: code = Unavailable desc = transport is closing
E0129 14:50:26.105056   23375 retry.go:19] shard clst.1.1 normal follow 0.1 still failed: pull changes: rpc error: code = Unavailable desc = transport is closing
I0129 14:50:26.105249   23375 master_event_processor.go:61] [master] - client [store@:8379] from 127.0.0.1:62477 keyspace(clst)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x44642af]

goroutine 218 [running]:
github.com/chrislusf/vasto/cmd/store.(*storeServer).processPut(0xc000169500, 0xc00020ca00, 0xc000454820, 0x0)
	/vasto/cmd/store/process_put.go:31 +0x15f
github.com/chrislusf/vasto/cmd/store.(*storeServer).processRequest(0xc000169500, 0xc000328208, 0x4, 0xc0002f4f60, 0xc0002f4f30)
	/vasto/cmd/store/store_tcp_server.go:153 +0x2ab
github.com/chrislusf/vasto/cmd/store.(*storeServer).handleInputOutput(0xc000169500, 0xc0000ee440, 0x1e, 0x1e, 0x1e, 0x0, 0x0, 0x6c1e838, 0x0)
	/vasto/cmd/store/store_tcp_server.go:91 +0x121
github.com/chrislusf/vasto/cmd/store.(*storeServer).handleRequest(0xc000169500, 0x46a2440, 0xc000191980, 0x6c1e838, 0xc000196020, 0x0, 0x0)
	/vasto/cmd/store/store_tcp_server.go:71 +0x117
github.com/chrislusf/vasto/cmd/store.(*storeServer).handleConnection(0xc000169500, 0x46abbc0, 0xc000196020)
	/vasto/cmd/store/store_tcp_server.go:47 +0xea
github.com/chrislusf/vasto/cmd/store.(*storeServer).serveTcp.func1(0x46abbc0, 0xc000196020, 0xc000304050, 0xc000169500)
	/vasto/cmd/store/store_tcp_server.go:36 +0xf7
created by github.com/chrislusf/vasto/cmd/store.(*storeServer).serveTcp
	/vasto/cmd/store/store_tcp_server.go:27 +0x14b
```

**Comment by lming** [comment]
Could be my local mistake. Closed for now.
